hunav_loader:
  ros__parameters:
    yaml_base_name: brownstone_agents
    simulator: Isaac Sim
    map: brownstone
    publish_people: true
    global_goals:
      1:
        x: 16.302
        y: -53.383
      2:
        x: 5.046
        y: 7.951
      3:
        x: 10.135
        y: -37.624
      4:
        x: 14.362
        y: -2.712
      5:
        x: 14.886
        y: -44.617
      6:
        x: 12.273
        y: -31.058
      7:
        x: 11.866
        y: 28.589
      8:
        x: 12.060
        y: -26.773
      9:
        x: 11.924
        y: 21.459
      10:
        x: 6.319
        y: -6.338
      11:
        x: 10.610
        y: 18.004
      12:
        x: 16.316
        y: -59.014
      13:
        x: 3.819
        y: -12.232
      14:
        x: 11.745
        y: -42.109
      15:
        x: 10.037
        y: -3.090
    agents:
      - agent1
      - agent2
      - agent3
      - agent4
      - agent5
      - agent6
      - agent7
      - agent8
    agent1:
      id: 1
      group_id: -1
      skin: 1
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 6.538
        y: -14.805
        z: -0.051
        h: -1.138
      behavior:
        type: Regular
        configuration: 1
        duration: 40.0
        once: true
        vel: 1.5
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 8
        - 6
        - 14
        - 5
        - 7
    agent2:
      id: 2
      group_id: -1
      skin: 2
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 6.776
        y: 11.977
        z: 0.000
        h: 1.073
      behavior:
        type: Regular
        configuration: 1
        duration: 40.0
        once: true
        vel: 1.5
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 9
        - 4
        - 10
        - 3
        - 5
    agent3:
      id: 3
      group_id: -1
      skin: 3
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 11.843
        y: 28.654
        z: -0.000
        h: -1.686
      behavior:
        type: Curious
        configuration: 1
        duration: 10.0
        once: false
        vel: 1.2
        dist: 10.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 11
        - 2
        - 3
        - 14
        - 5
    agent4:
      id: 4
      group_id: -1
      skin: 4
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 16.316
        y: -51.315
        z: -0.051
        h: 1.768
      behavior:
        type: Regular
        configuration: 1
        duration: 40.0
        once: true
        vel: 1.5
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 6
        - 13
        - 10
        - 4
        - 11
    agent5:
      id: 5
      group_id: -1
      skin: 5
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 13.271
        y: -41.073
        z: -0.051
        h: 1.888
      behavior:
        type: Regular
        configuration: 1
        duration: 40.0
        once: true
        vel: 1.5
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 13
        - 15
        - 2
        - 9
        - 7
    agent6:
      id: 6
      group_id: -1
      skin: 6
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 10.627
        y: -2.295
        z: -0.051
        h: -2.388
      behavior:
        type: Regular
        configuration: 1
        duration: 40.0
        once: true
        vel: 1.5
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 10
        - 2
        - 7
        - 8
        - 12
    agent7:
      id: 7
      group_id: -1
      skin: 7
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 4.049
        y: -13.177
        z: -0.051
        h: 1.250
      behavior:
        type: Scared
        configuration: 1
        duration: 8.0
        once: false
        vel: 1.8
        dist: 5.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 10
        - 4
        - 11
        - 9
        - 8
    agent8:
      id: 8
      group_id: -1
      skin: 8
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 13.256
        y: 26.568
        z: -0.000
        h: -1.826
      behavior:
        type: Curious
        configuration: 1
        duration: 10.0
        once: false
        vel: 1.2
        dist: 10.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 9
        - 10
        - 14
        - 5
        - 1

hunav_isaac_authoring:
  ros__parameters:
    navmesh:
      settings_digest: 1d491be179b6
      volume_min: [-4.491, -63.583, -2.619]
      volume_max: [18.266, 31.438, 2.500]
      ground_z: 0.000
      sampling_cm: 30.0
      assigned_prims:
        - /World/Environment/ParkDeOv/Geometry/Pathways/Mesh_7dcc7d3c1173417d8c7fd83bce581583
        - /World/Environment/ParkDeOv/Geometry/Grass/Mesh_0d6fe94e007840c69b62ea5908848e4d
        - /World/Environment/ParkDeOv/Geometry/Hardscape/Adjusted/Mesh_95da68790a88447e89f656771f7027a3
        - /World/Environment/ParkDeOv/Geometry/Pathways/Mesh_2dbfb2b335394f5ab1112d2cbed1dd8a
        - /World/Environment/ParkDeOv/Geometry/Pathways/Mesh_1b524b3b371d4009b7b9d8a82062f342
      assigned_mesh_count: 5
      bake_settings:
        agentHeight: 2.0
        agentMaxClimb: 0.9
        agentMaxSlope: 45.0
        agentMinIslandRadius: 2.0
        agentMinRadius: null
        agentRadius: 0.6
        cellSize: 0.3
        excludeRigidBodies: true
        useGpu: true
