hunav_loader:
  ros__parameters:
    yaml_base_name: brownstone_agents
    simulator: Isaac Sim
    map: brownstone
    publish_people: true
    global_goals:
      1:
        x: 2.112
        y: -8.478
      2:
        x: -30.213
        y: -24.955
      3:
        x: -6.524
        y: -41.253
      4:
        x: -31.814
        y: -70.564
      5:
        x: -2.272
        y: -31.124
      6:
        x: -9.476
        y: 7.417
      7:
        x: 13.281
        y: 0.351
      8:
        x: -43.188
        y: 19.421
      9:
        x: 14.232
        y: -10.896
      10:
        x: -12.590
        y: -7.585
      11:
        x: -29.450
        y: -4.559
      12:
        x: 17.457
        y: 12.194
      13:
        x: -25.697
        y: 25.462
      14:
        x: 5.573
        y: -47.441
      15:
        x: 17.996
        y: -36.977
    agents:
      - agent1
      - agent2
      - agent3
      - agent4
      - agent5
      - agent6
      - agent7
      - agent8
    agent1:
      id: 1
      group_id: -1
      skin: 1
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 1.439
        y: 2.845
        z: -0.000
        h: 2.745
      behavior:
        type: Regular
        configuration: 1
        duration: 40.0
        once: true
        vel: 1.5
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 6
        - 7
        - 5
        - 13
        - 8
    agent2:
      id: 2
      group_id: -1
      skin: 2
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -39.334
        y: -67.358
        z: -0.002
        h: -0.403
      behavior:
        type: Regular
        configuration: 1
        duration: 40.0
        once: true
        vel: 1.5
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 4
        - 3
        - 5
        - 10
        - 9
    agent3:
      id: 3
      group_id: -1
      skin: 3
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -31.460
        y: -32.811
        z: 0.000
        h: 1.413
      behavior:
        type: Curious
        configuration: 1
        duration: 10.0
        once: false
        vel: 1.2
        dist: 10.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 2
        - 10
        - 5
        - 3
        - 13
    agent4:
      id: 4
      group_id: -1
      skin: 4
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -17.256
        y: 26.099
        z: -0.014
        h: -1.433
      behavior:
        type: Regular
        configuration: 1
        duration: 40.0
        once: true
        vel: 1.5
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 10
        - 9
        - 12
        - 15
        - 3
    agent5:
      id: 5
      group_id: -1
      skin: 5
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -11.605
        y: 6.391
        z: 0.000
        h: 2.207
      behavior:
        type: Regular
        configuration: 1
        duration: 40.0
        once: true
        vel: 1.5
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 13
        - 7
        - 5
        - 14
        - 2
    agent6:
      id: 6
      group_id: -1
      skin: 6
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -19.675
        y: -71.507
        z: -0.000
        h: 1.793
      behavior:
        type: Regular
        configuration: 1
        duration: 40.0
        once: true
        vel: 1.5
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 2
        - 6
        - 7
        - 9
        - 8
    agent7:
      id: 7
      group_id: -1
      skin: 7
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -41.453
        y: -31.982
        z: -0.000
        h: 1.158
      behavior:
        type: Scared
        configuration: 1
        duration: 8.0
        once: false
        vel: 1.8
        dist: 5.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 11
        - 10
        - 6
        - 9
        - 4
    agent8:
      id: 8
      group_id: -1
      skin: 8
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -25.457
        y: 26.757
        z: -0.000
        h: -2.749
      behavior:
        type: Curious
        configuration: 1
        duration: 10.0
        once: false
        vel: 1.2
        dist: 10.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 8
        - 1
        - 9
        - 5
        - 15

hunav_isaac_authoring:
  ros__parameters:
    navmesh:
      settings_digest: 6f7a13b534b7
      volume_min: [-53.000, -85.000, -2.000]
      volume_max: [32.000, 44.950, 4.000]
      ground_z: 0.000
      sampling_cm: 20.0
